### ISSUE TITLE
ERROR: Please rename sequences listed above!

### ISSUE THREAD

**Issue by tseemann** [MDU-PHL/arbow#13]
I accidently gave an unaligned file and got this backtrace?

```
% arbow -t 36 ../raw.ffn 

INFO:root:Loading FASTA alignment...
INFO:root:Loaded 1164 sequences
INFO:root:Trimming according to ref sequence...
INFO:root:Found 0 introduced gaps into the ref...
INFO:root:New alignment length: 29906...
INFO:root:Trimming 5' and 3' UTR regions...
INFO:root:Clean alignment length: 29409
INFO:root:Getting column stats...
WARNING:root:Not filtering out any sites with missing data.
INFO:numexpr.utils:Note: detected 72 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
INFO:numexpr.utils:Note: NumExpr detected 72 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:root:Total included sites: 29409
INFO:root:Finding constant sites...
INFO:root:Filtering constant sites by 1 max minor allele count and not allowing missing sites.
INFO:root:Total constant sites: 39
INFO:root:Total variable sites: 29370
INFO:root:Wrote variable sites to arbow-aln-2020-05-11-163508.aln
INFO:root:Constant site counts - A:11 | C:5 | G:10 | T:10
INFO:root:Running: iqtree -s arbow-aln-2020-05-11-163508.aln -pre arbow-tree-2020-05-11-163508 -mset HKY,TIM2,GTR -mfreq F -mrate G,R -bb 1000 -alrt 1000 -nt 36 -fconst 11,5,10,13
ERROR: Please rename sequences listed above!
INFO:root:Writing out separate trees for BB and aLRT....
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/arbow", line 8, in <module>
    sys.exit(main())
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/arbow/__main__.py", line 639, in main
    output_separate_trees(prefix)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/arbow/__main__.py", line 378, in output_separate_trees
    with open(treefile) as tr, open(bbtree, "w") as bb, open(alrttree, "w") as alrt:
FileNotFoundError: [Errno 2] No such file or directory: 'arbow-tree-2020-05-11-163508.treefile'

````

**Comment by andersgs** [comment]
Interesting... That is an IQTree error... I'll add something to pick up on unaligned sequence input. 

I think this is related to #6
